apiVersion: v1
appVersion: 1.11.2
description: Chart for Apache Flink
name: flink_1_11
version: 0.0.3
maintainers:
  - name: charts-maintainers
    email: charts-maintainers@riskfocus.com
home: https://github.com/riskfocus/helm-charts-public
